### ISSUE TITLE
This repo is amazing. How did you create it?

### ISSUE THREAD

**Issue by peabnuts123** [futsuki/UnityEngine.d.ts#1]
Hi,

I realise it's a bit unorthodox to create an issue as a comment but GitHub kind of lacks communication features for some reason.
I am looking into compiling TypeScript to JavaScript to run in Unity, but I needed a type definition set to compile the native Unity functionality, BUT THANKFULLY YOU'VE ALREADY DONE THIS so good job on this repo, really.

I have a question though, how did you create it? I can only assume it was done with some kind of tool. I would be interested in maintaining something like this going forward, to enable others to develop Unity using TypeScript, potentially make an Asset on the store for setting up a workflow etc. So I would like to know how this was done so that I may contribute going forwards / run a fork myself.

Thanks.

**Comment by futsuki** [comment]
(Machine translation)
Hello.
I'm sorry to reply so late.
I added a type definition extraction tool to the repository.
I am pleased if this helps.
Thank you.

> (Original)
> こんにちは。
> 返信がとても遅れてごめんなさい。
> 型定義の抽出ツールをリポジトリに追加しました。
> これが助けになれば幸いです。
> ありがとう。

**Comment by peabnuts123** [comment]
Thank for replying! Do you know which tool you used? I would love to look at it myself.

**Comment by futsuki** [comment]
(Machine translation)
After copying `dtsextractor` directory of this repository to Unity project, it can be launched from` Window/*.d.ts Extractor` menu in Unity.
`TypescriptDefinitionWriter.cs` does not depend on Unity, so it may be usable in other environments.

> (Original)
> このリポジトリの`dtsextractor`ディレクトリをUnityのプロジェクトにコピーした後、Unity内の`Window/*.d.ts Extractor`メニューから起動できます。
> `TypescriptDefinitionWriter.cs`はUnityに依存していないので、他の環境でも使えるかもしれません。

**Comment by peabnuts123** [comment]
Thanks for the information!
